# Generated by Django 4.0.4 on 2022-05-27 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 16, 41, 28, 997483, tzinfo=utc)),
        ),
    ]
